---
spring:
  application:
    name: "multipleinstances"
  datasource:
    url: "jdbc:postgresql://db:5432/shedlock"
    username: "vien.huynh"
    password: "123456"
    driver-class-name: "org.postgresql.Driver"
