---
name: "spring-batch"
services:
  backend:
    image: "spring-batch:0.1.0"
    scale: 5
    depends_on:
      - "db"
  db:
    image: "postgres:13.22"
    environment:
      POSTGRES_DB: "shedlock"
      POSTGRES_USER: "vien.huynh"
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
