---
spring:
  application:
    name: "spring-batch"
  datasource:
    url: "jdbc:postgresql://db:5432/spring-batch"
    username: "vien.huynh"
    password: "123456"
    driver-class-name: "org.postgresql.Driver"
